### PR TITLE
DOC: Created install and updated Agg ref URL

### PR DESCRIPTION
**Pull request by cpelley**
1. Creates first stage INSTALL file.
2. Updates agg reference URL to the location where it it maintained (sourceforge).

Project github summary description will need URL updating following the merge of this PR.

### CODE REVIEW

**Comment by rhattersley** [comment]
Looks fine. :+1: Are you waiting for someone to merge this? Or are you planning to merge yourself? I.e. how do you want to run the workflow?

**Comment by cpelley** [comment]
> Are you waiting for someone to merge this? Or are you planning to merge yourself? I.e. how do you want to run the workflow?

In all honesty, I had not given workflow any thought up to now.  I assumed that it would share a common workflow with https://github.com/SciTools (reviewer merges the changes).  I would propose we follow this workflow until we have reason to follow a different path.  Do you agree?

Thanks @rhattersley.

**Comment by rhattersley** [comment]
> I would propose we follow this workflow until we have reason to follow a different path. Do you agree?

It's fine by me. :smile: I'm happy to go along with (almost :wink:) whatever you suggest. My only concern with using the fairly strict no-self-merging model from Iris is that you'll be held up too much.

NB. The SciTools projects don't all have the same stance on self-merging.

**Comment by rhattersley** [comment]
> Project github summary description will need URL updating following the merge of this PR.

Done. :smile:

**Comment by cpelley** [comment]
Thanks @rhattersley.
Project github summary description URL updated.

**Pull request merged**
